slam_toolbox:
  ros__parameters:
    # Robot frame settings
    odom_frame: odom
    base_frame: base_footprint
    map_frame: map

    # SLAM mode settings
    mode: mapping  # mapping or localization
    debug_logging: false
    throttle_scans: 1
    transform_publish_period: 0.02
    map_update_interval: 5.0
    resolution: 0.05
    max_laser_range: 20.0  # Adjust based on your lidar specs
    minimum_time_interval: 0.5
    transform_timeout: 0.2
    tf_buffer_duration: 30.0

    # Scan matcher parameters
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.5
    minimum_travel_heading: 0.5
    scan_buffer_size: 10
    scan_buffer_maximum_scan_distance: 10.0
    link_match_minimum_response_fine: 0.1
    link_scan_maximum_distance: 1.5
    loop_search_maximum_distance: 3.0
    do_loop_closing: true
    loop_match_minimum_chain_size: 3
    loop_match_maximum_variance_coarse: 3.0
    loop_match_minimum_response_coarse: 0.35
    loop_match_minimum_response_fine: 0.45

    # Correlation parameters
    correlation_search_space_dimension: 0.5
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.1

    # Correlation parameters - coarse
    coarse_search_space_dimension: 0.3
    coarse_search_space_resolution: 0.01
    coarse_search_space_smear_deviation: 0.03

    # Scan matcher parameters
    fine_search_angle_offset: 0.00349  # ~0.2 degrees
    coarse_search_angle_offset: 0.349   # ~20 degrees
    fine_search_xy_window: 0.2
    coarse_search_xy_window: 1.0
    use_response_expansion: true